import Footer from "./components/Footer";
import Header from "./components/Header";
import "./globals.css";

export const metadata = {
  title: "Elsa Hovey | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="w-[100%]">
        <Header />
        <main className="bg-moonstone">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
